image: maven:3.9.6-eclipse-temurin-21

variables:
  # Ho aggiunto le opzioni per JavaFX (headless=false e rendering software) accanto alla tua config della cache
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Djava.awt.headless=false -Dprism.order=sw -Dprism.text=t2k"

cache:
  paths:
    - .m2/repository/

stages:
  - test
  - build

test_and_coverage:
  stage: test
  script:
    - apt-get update && apt-get install -y libgtk-3-0 libgl1-mesa-glx xvfb libxtst6 libasound2 libx11-6 libx11-xcb1 libxi6 libxrender1

    - cd msvm-studio

    - xvfb-run -a -s "-screen 0 1024x768x24" mvn clean verify


    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print "Total Coverage:", 100*covered/instructions, "%" }' target/site/jacoco/jacoco.csv

  coverage: '/Total Coverage: ([0-9]{1,3}\.[0-9]*)/'
  artifacts:
    when: always
    reports:
      junit: msvm-studio/target/surefire-reports/TEST-*.xml
      coverage_report:
        coverage_format: jacoco
        path: msvm-studio/target/site/jacoco/jacoco.xml
    paths:
      - msvm-studio/target/site/jacoco/

package-app:
  stage: build
  tags:
    - Luca_Runner
    - arben-main-pc
  script:
    - cd msvm-studio
    - mvn clean package -DskipTests # skip test in quanto gia fatti
  artifacts:
    paths:
      - msvm-studio/target/*.jar
  needs:
    - job: test_and_coverage